### ISSUE TITLE
Solarized Colors not working on powershell.

### ISSUE THREAD

**Issue by learning-powershell** [neilpa/cmd-colors-solarized#14]
Hi,

I am using Windows 7, 32 bit. I did `regedit /s solarized-dark.reg` and got the beautiful colors in CMD.exe but my PowerShell (v 4.0) still remains the same. When I run the following code:
```
$Host.PrivateData.DebugBackgroundColor = "Black"
$Host.PrivateData.ErrorBackgroundColor = "Black"
function Out-Colors()
{
    [enum]::GetValues([ConsoleColor]) | % {
        Write-Host -NoNewLine "$($_.value__) : $_`t"
        Write-Host "COLOR`t" -ForegroundColor $_ -NoNewLine
        Write-Host "`t" -BackgroundColor $_
    }
}
Out-Colors
```
![capture](https://cloud.githubusercontent.com/assets/24669137/21344673/f48caf08-c6c2-11e6-8215-f2da3c0eba22.PNG)
This is what I got.

How can I make my powershell look like the one in your `readme.md`

**Comment by TBBle** [comment]
You're probably running the shell via a shortcut (e.g. `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Windows PowerShell`). The shortcuts have their own colour settings. I fixed this by copying the colour values into the shortcut from the defaults property page for a running cmd.exe.

**Comment by samirotiv** [comment]
Hi,
Although I ran powershell from Windows > Run, but the background color still doesn't seem to change. The text colow has changed, though. Any idea what I can do?

**Comment by TBBle** [comment]
@samirotiv There's probably a registry key in `HKEY_CURRENT_USER\Console` for `%SystemRoot%_System32_WindowsPowerShell_v1.0_powershell.exe` which contains entries overriding the registry setting you've imported.

You can either delete/rename those keys (`PopupColors`, `ScreenColors` and anything starting with `ColorTable`), or update them to match the registry file you chose ([solarized-dark.reg](https://github.com/neilpa/cmd-colors-solarized/blob/master/solarized-dark.reg) or [solarized-light.reg](https://github.com/neilpa/cmd-colors-solarized/blob/master/solarized-light.reg)).

There's also (on a 64-bit system) a `%SystemRoot%_SysWOW64_WindowsPowerShell_v1.0_powershell.exe` key for the 32-bit powershell executable.

To rule out anything else odd (Powershell-specific configuration), you can run `powershell` inside a `cmd` window, and if the colours were correct in cmd, they should be correct in that powershell instance.
